[2021-07-18T11:58:46.579599+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T11:58:46.581175+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T11:58:46.581182+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T11:58:46.581189+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T11:58:46.631573+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:01:46.477637+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:01:46.481061+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:01:46.481068+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:01:46.481072+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:01:46.558786+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:04:25.534793+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:04:25.538239+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:04:25.538246+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:04:25.538251+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:04:25.615370+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:15:22.423728+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:15:22.427153+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:15:22.427160+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:15:22.427164+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:15:22.505369+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:19:48.430679+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:19:48.434178+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:19:48.434185+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:19:48.434190+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:19:48.512081+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:25:02.147766+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:25:02.151225+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:25:02.151232+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:25:02.151237+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:25:02.229717+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:34:45.714982+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:34:45.718423+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:34:45.718430+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:34:45.718435+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:34:45.795890+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:43:40.748704+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:43:40.752296+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:43:40.752303+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:43:40.752308+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:43:40.834664+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:52:00.162870+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:52:00.166376+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:52:00.166382+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:52:00.166387+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:52:00.243522+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test'" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'met_user'@'%' to database 'met_db_test' at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
[2021-07-18T12:55:30.507603+00:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'met_user1'@'192.168.32.2' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'met_user1'@'192.168.32.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'met_user1'@'192.168.32.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'met_user1'@'192.168.32.2' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'met_user1'@'192.168.32.2' (using password: YES)"} []
[2021-07-18T12:55:30.508356+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-07-18T12:59:33.326601+00:00] request.INFO: Matched route "subscription_form_viiew". {"route":"subscription_form_viiew","route_parameters":{"_route":"subscription_form_viiew","_controller":"Sergeydrak\\SubscriptionBundle\\Controller\\SubscriptionFormViewController::index"},"request_uri":"http://localhost/","method":"GET"} []
[2021-07-18T12:59:33.330153+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2021-07-18T12:59:33.330159+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:59:33.330164+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"App\\Security\\UserAuthenticator"} []
[2021-07-18T12:59:33.407483+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:39)"} []
